//! generated by claude-3.5-sonnet at Nov 21, 2024

use std::ops::Add;

// Generic add function
pub fn add_generic<T: Add<Output = T>>(a: T, b: T) -> T {
    a + b
}

// Explicit instantiation for int (equivalent to template int add_generic<int>)
pub extern "C" fn add_generic_int(a: i32, b: i32) -> i32 {
    add_generic(a, b)
}

// Float version is commented out in C++, but would be:
pub extern "C" fn add_generic_float(a: f32, b: f32) -> f32 {
    add_generic(a, b)
}
