//! generated by claude-3.5-sonnet at Nov 20, 2024
//! validation result: a seemingly correct translation of `simple_enum.cpp`

#[repr(i32)]  // Use same representation as C++ enum
#[derive(Clone, Copy)]  // Make it work like C++ value type
pub enum Color {
    Red = 0,
    Green = 1,
    Blue = 2,
}

pub fn create_color(x: i32) -> Color {
    // Directly transmute the integer to enum, matching C++'s behavior
    unsafe { std::mem::transmute(x) }
}
